-- Alur Scrap Inventory & Peleburan (spec: Final Alur Modul Bahan Baku, Scrap, Buyback)
-- 1. sumber_ref: kunci upsert untuk scrap otomatis (SH:<stage_handover_id> serbuk produksi, BB:<buyback_id> buyback reject)
-- 2. gramasi: info gramasi asal (serbuk produksi / buyback)
-- 3. scrap_usage: audit trail pemakaian scrap per peleburan (partial usage)

ALTER TABLE scrap_inventory ADD COLUMN IF NOT EXISTS sumber_ref text;
ALTER TABLE scrap_inventory ADD COLUMN IF NOT EXISTS gramasi text;
ALTER TABLE scrap_inventory ADD COLUMN IF NOT EXISTS berat_terpakai numeric DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS scrap_inventory_sumber_ref_key
  ON scrap_inventory (sumber_ref) WHERE sumber_ref IS NOT NULL AND voided_at IS NULL;

CREATE TABLE IF NOT EXISTS scrap_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scrap_id bigint NOT NULL REFERENCES scrap_inventory(id),
  peleburan_id bigint REFERENCES peleburan(id),
  peleburan_kode text,
  gram numeric NOT NULL,
  created_by uuid,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS scrap_usage_scrap_id_idx ON scrap_usage (scrap_id);
CREATE INDEX IF NOT EXISTS scrap_usage_peleburan_id_idx ON scrap_usage (peleburan_id);

ALTER TABLE scrap_usage ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "authenticated read scrap_usage" ON scrap_usage
    FOR SELECT TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "authenticated write scrap_usage" ON scrap_usage
    FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
